const app = document.querySelector('#app');
const labels = { OFFICIAL: 'Confirmé officiellement', REPORTED: 'À recouper', UNCONFIRMED: 'Rumeur / non confirmé', UPCOMING: 'À venir', LIVE: 'En direct', COMPLETED: 'Terminé', TBC: 'Date à confirmer' };
let data, selectedId = null, filterBrand = 'ALL', filterStatus = 'ALL';
const escape = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
const dateFormat = (date, timezone) => new Intl.DateTimeFormat('fr-FR', { dateStyle:'full', timeStyle:'short', timeZone: timezone || 'UTC' }).format(new Date(date));
const isDone = event => event.status !== 'TBC' && new Date(event.date).getTime() <= Date.now();
const effectiveStatus = event => isDone(event) ? 'COMPLETED' : event.status;
const filtered = () => data.events.filter(e => (filterBrand === 'ALL' || e.brand === filterBrand) && (filterStatus === 'ALL' || effectiveStatus(e) === filterStatus));
function countdown(e) { if (effectiveStatus(e) === 'COMPLETED') return '<span class="count-end">Événement terminé</span>'; if (e.status === 'TBC') return '<span class="count-end">Date en attente</span>'; const delta = Math.max(0, new Date(e.date) - Date.now()); const d = Math.floor(delta / 864e5), h = Math.floor(delta / 36e5) % 24, m = Math.floor(delta / 6e4) % 60, s = Math.floor(delta / 1e3) % 60; return [[d,'JOURS'],[h,'HEURES'],[m,'MIN'],[s,'SEC']].map(([n,l])=>`<span><b>${String(n).padStart(2,'0')}</b><small>${l}</small></span>`).join('<i>:</i>'); }
function deviceArt(e) { return e.image ? `<img src="${escape(e.image)}" alt="${escape(e.name)}" onerror="this.remove()">` : `<div class="device-art"><div class="camera"></div><div class="glow"></div><span>${escape(e.brand.slice(0,2))}</span></div>`; }
function links(e) { const map = [['officialUrl','Page officielle','↗'],['productUrl','Produit','◈'],['eventUrl','Événement','◌'],['streamUrl','Diffusion','▶'],['youtubeUrl','YouTube','◉'],['pressUrl','Kit presse','▣'],['reservationUrl','Réserver','→']]; return map.filter(([key])=>e[key]).map(([key,label,icon])=>`<a href="${escape(e[key])}" target="_blank" rel="noreferrer">${icon} ${label}</a>`).join(''); }
function render() { const events = filtered(); const selected = data.events.find(e=>e.id===selectedId) || events[0] || null; if (selected) selectedId = selected.id;
 const brands = [...new Set(data.events.map(e=>e.brand))].sort(); const monthName = new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(new Date(`${data.month}-01T12:00:00Z`));
 const confirmed = data.events.filter(e=>e.confidence==='OFFICIAL').length, upcoming=data.events.filter(e=>effectiveStatus(e)==='UPCOMING').length, completed=data.events.filter(e=>effectiveStatus(e)==='COMPLETED').length;
 app.innerHTML = `<header><a class="brand" href="#" aria-label="Accueil"><span class="brand-orbit">◌</span><span>SMARTPHONE<br><b>LAUNCH RADAR</b></span></a><div class="month"><span>RADAR MENSUEL</span><strong>${escape(monthName)}</strong></div><div class="controls"><label><span>Fabricant</span><select id="brand-filter"><option value="ALL">Tous</option>${brands.map(b=>`<option ${b===filterBrand?'selected':''}>${escape(b)}</option>`).join('')}</select></label><label><span>Statut</span><select id="status-filter"><option value="ALL">Tous les statuts</option>${['UPCOMING','LIVE','COMPLETED','TBC'].map(s=>`<option value="${s}" ${s===filterStatus?'selected':''}>${labels[s]}</option>`).join('')}</select></label><button class="refresh" id="refresh" aria-label="Actualiser">↻</button></div></header>
 <section class="intro"><div><p class="eyebrow">SIGNAL INTELLIGENCE / ${data.month}</p><h1>Les prochains <em>signaux</em><br>du marché mobile.</h1><p class="lede">Un calendrier transparent des lancements, où chaque date conserve son niveau de vérification.</p></div><div class="source-note"><span>◈ SOURCE STATUS</span>${escape(data.sourcesNote)}</div></section>
 <section class="workspace"><div class="timeline-panel"><div class="panel-heading"><div><span class="eyebrow">CHRONOLOGIE</span><h2>Événements du mois</h2></div><span class="count">${events.length} SIGNAL${events.length===1?'':'S'}</span></div><div class="timeline">${events.length ? events.map((e,i)=>`<button class="event-card ${e.id===selectedId?'selected':''} ${effectiveStatus(e).toLowerCase()}" data-id="${escape(e.id)}"><div class="card-art">${deviceArt(e)}<span class="status ${effectiveStatus(e)}">${labels[effectiveStatus(e)]}</span></div><div class="card-content"><p>${escape(e.brand)} · ${e.status==='TBC'?'DATE À CONFIRMER':escape(new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short'}).format(new Date(e.date)))}</p><h3>${escape(e.name)}</h3><span class="confidence ${e.confidence}">${labels[e.confidence]}</span></div>${i < events.length-1?'<div class="connector"></div>':''}</button>`).join('') : `<div class="empty"><div>⌁</div><h3>Aucun lancement vérifié</h3><p>Le radar n’affiche aucune date non sourcée comme un fait. Revenez après la prochaine mise à jour de nos sources officielles.</p></div>`}</div></div>
 <aside class="details">${selected ? `<div class="detail-art">${deviceArt(selected)}<div class="detail-status"><span class="status ${effectiveStatus(selected)}">${labels[effectiveStatus(selected)]}</span><span class="confidence ${selected.confidence}">${labels[selected.confidence]}</span></div></div><div class="detail-body"><p class="eyebrow">FICHE ÉVÉNEMENT</p><h2>${escape(selected.name)}</h2><p class="detail-brand">${escape(selected.brand)} <i></i> ${escape(selected.region)}</p><div class="date-row"><span>◷</span><div><b>${selected.status==='TBC'?'Date à confirmer':dateFormat(selected.date,selected.timezone)}</b><small>${escape(selected.timezone)}</small></div></div><div class="clock" data-clock>${countdown(selected)}</div><p class="summary">${escape(selected.summary)}</p><h4>INFORMATIONS CONFIRMÉES</h4><ul>${Object.entries(selected.specifications).map(([k,v])=>`<li><span>${escape(k)}</span><b>${escape(v)}</b></li>`).join('')}</ul><div class="links">${links(selected)}</div></div>` : `<div class="empty detail-empty"><div>◎</div><h2>Radar en veille</h2><p>Sélectionnez un événement lorsqu’une annonce vérifiée est disponible.</p></div>`}</aside></section>
 <footer><div class="stats"><span><b>${data.events.length}</b> événements</span><span><b>${confirmed}</b> confirmés</span><span><b>${upcoming}</b> à venir</span><span><b>${completed}</b> terminés</span></div><p>Les données <b>OFFICIAL</b> proviennent des fabricants. Les autres niveaux ne sont jamais présentés comme confirmés.</p></footer>`;
 document.querySelector('#brand-filter').onchange=e=>{filterBrand=e.target.value;render()}; document.querySelector('#status-filter').onchange=e=>{filterStatus=e.target.value;render()}; document.querySelector('#refresh').onclick=()=>location.reload(); document.querySelectorAll('.event-card').forEach(x=>x.onclick=()=>{selectedId=x.dataset.id;render()});
}
async function init() { try { const response = await fetch('./data/events.json'); if (!response.ok) throw new Error('Données indisponibles'); data = await response.json(); render(); setInterval(()=>{if(document.querySelector('[data-clock]')) document.querySelector('[data-clock]').innerHTML=countdown(data.events.find(e=>e.id===selectedId));},1000); } catch (error) { app.innerHTML=`<div class="fatal"><h1>Radar indisponible</h1><p>${escape(error.message)}</p><button onclick="location.reload()">Réessayer</button></div>`; } }
init();
